config/routes.rb
require 'api_constraints'

Backstage::Application.routes.draw do

  devise_for :members

  concern :notable do
    resources :notes
  end

  concern :sortable do
    collection { post :reposition }
  end

  # API Calls
  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :members do
        get :conflicts
      end

      get 'event/:id',    to: 'events#event'
      get 'events/:date', to: 'events#events'
    end
  end

  resources :announcements, controller: 'messages', :as => :messages do
    get :approve
    get :resend_email
  end

  resource :inbox, controller: 'inbox', :only => [:show,:create] # For email WebHooks

  resources :skills,  :concerns => :sortable

  resources :show_templates, except: [:show]
  resources :shows,   :concerns => :notable do
    collection do
      get 'create',   to: 'shows#create_shows', as: 'create'
    end
    post 'casting_announcement'
  end

  get '/members/schedule'
  resources :members, :concerns => :notable do
    get :cast_list
    resource :conflicts do
      get :manage_conflicts, :as => :manage
      get :get_conflicts,  :as => :get
      put :set_conflicts,  :as => :set
    end
  end
  get '/conflicts',      to: 'conflicts#index'
  put '/lock_conflicts', to: 'conflicts#lock_conflicts'
  get '/roles',          to: 'members#roles'

  resources :configs, controller: 'konfigs', only: [ :index, :update ] do
    collection do
      patch :update_multiple
    end
  end

  resources :documents, only: [:index, :new, :create, :destroy]   

  # Shifts
  get   '/shifts', to: 'shifts#index'
  patch '/shifts', to: 'shifts#update'
  get 'shifts/schedule'
  get 'shifts/publish'

  # Audit logs
  get '/audit',       to: 'audits#index'
  get '/audit/:type', to: 'audits#index'

  # Used for testing (inactive when in production mode)
  get '/admin', to: 'members#admin'

  root 'members#show'

end

app/models/message.rb
class Message < ActiveRecord::Base
  include MessagesHelper

  has_and_belongs_to_many :members, autosave: true
  belongs_to :sender,   class_name: Member, :foreign_key => :sender_id
  belongs_to :approver, class_name: Member, :foreign_key => :approver_id
  before_save :check_and_add_members

  scope :by_created,   -> { order(:created_at   => :desc) }
  scope :by_sent,      -> { order(:sent_at      => :desc) }
  scope :by_delivered, -> { order(:delivered_at => :desc) }

  scope :recent,   -> { where('messages.created_at >= ?', (Date.today - 2.weeks) ) }
  scope :approved, -> { where.not(approver: nil) }

  scope :for_member, ->(member) {
    joins(:members).where('sender_id = ? OR ( members.id = ? AND approver_id IS NOT NULL )',
                          member.id, member.id).uniq
  }

  alias_attribute :text, :message

  validates_presence_of :subject, :message

  def approved?
    !approver.nil?
  end

  def sent?
    !sent_at.nil?
  end

  def delivered?
    !delivered_at.nil?
  end

  def formatted_text(format = nil)
    markdown message, format
  end

  def date
    created_at.strftime('%m/%d/%Y')
  end

  def time_stamp(column = :delivered, format_type = :short)
    column = column.to_s + '_at'
    if self.respond_to?(column) and !self.send(column).nil?
      format = format_type.to_sym == :short ? '%m/%d/%Y %I:%M:%S %p' : '%A%n%B %e, %Y%nat %I:%M:%S %p'
      self.send(column).strftime(format)
    else
      'N/A'
    end
  end

  def status_class
    return 'status-red'    if !approved?
    return 'status-yellow' if !delivered?
    'status-green'
  end

  private

  def check_and_add_members
    self.members = Member.company_members.to_a.uniq if self.members.empty?
  end

end

app/models/show.rb
class Show < ActiveRecord::Base
  before_destroy :log_destroy
  before_save    :set_capacity

  store_accessor :tickets

  has_many :shifts, :dependent => :destroy
  has_many :crew_members, :through => :shifts, :source => :member
  has_many :skills, -> { order(:code) }, :through => :shifts
  has_many :scenes, -> { order(:position) }, :dependent => :destroy
  has_many :notes, :as => :notable

  belongs_to :mc, class_name: 'Member', :inverse_of => :mc_shifts
  belongs_to :group, class_name: 'Role'

  has_and_belongs_to_many :actors, class_name: 'Member', join_table: 'actors_shows'

  accepts_nested_attributes_for :scenes, allow_destroy: true
  accepts_nested_attributes_for :shifts, allow_destroy: true

  scope :recent, -> { where('date > ?', Date.today - 5.days) }
  scope :by_date, -> { order(:date, :showtime) }
  scope :by_date_desc, -> { order(:date => :desc, :showtime => :desc) }

  scope :for_date, ->(date) { where(date: date) }
  scope :for_month, ->(cdate = Date.today) { where('date >= ? AND date <= ?', cdate.beginning_of_month, cdate.end_of_month) }

  # default_scope { by_date }

  validates_presence_of :date, :name

  def call_time
    calltime.strftime('%l:%M %P')
  end

  def show_time
    showtime.strftime('%l:%M %P')
  end

  def casting_sent
    casting_sent_at.strftime('%m/%d/%Y @ %l:%M %P')
  end

  def gregorian_date
    date.strftime('%m/%d/%Y')
  end

  def human_date
    case date
      when Date.today     then 'Today'
      when Date.tomorrow  then 'Tomorrow'
      when Date.yesterday then 'Yesterday'
      else gregorian_date
    end
  end

  def year
    date.strftime('%Y').to_i
  end

  def month
    date.strftime('%m').to_i
  end

  def dow
    date.strftime('%A')
  end

  def datetime
    "#{gregorian_date} @ #{show_time}"
  end

  def title
    "#{datetime} - #{name}"
  end

  def cal_title
    "#{show_time} - #{name}"
  end

  def dowtitle
    "#{datetime} #{dow}"
  end

  def shift(code = nil)
    return unless code
    shifts.where(skill: Skill.class_eval(code.to_s.downcase)).first
  end

  def cast?
    !casting_sent_at.nil?
  end

  def to_datetime(time = :showtime)
    DateTime.new(date.year, date.month, date.day, self.send(time).in_time_zone('UTC').hour, self.send(time).in_time_zone('UTC').min)
  end

  def is_soon?
    ( 6.hours.ago.to_datetime.utc .. 24.hours.from_now.to_datetime.utc ).cover?(to_datetime)
  end

  def is_today?
    date == Date.today
  end

  def self.ticket_types
    %w(sold comp rush walkup)
  end

  def tickets_total
    Show.ticket_types.map { |t| tickets_for_type(t) }.inject(:+)
  end

  def sold_out?
    tickets_total >= ( capacity || Konfig.default_show_capacity )
  end

  # Provides accessor methods for all ticket_types
  def method_missing(method, *args)
    if Show.ticket_types.include?(method.to_s)
      tickets_for_type(method.to_s)
    else
      super
    end
  end

  def respond_to?(method, include_private = false)
    if Show.ticket_types.include?(method.to_s)
      true
    else
      super
    end
  end

  private

  def tickets_for_type(type)
    return 0 if tickets.nil?
    tickets.has_key?(type.to_s) ? tickets[type.to_s].to_i : 0
  end

  def set_capacity
    self.capacity ||= Konfig.default_show_capacity
  end

  def log_destroy
    Audit.logger self.class.to_s, "Deleted #{self.title}"
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  authorize_resource

  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :set_members, only: [:new, :create, :edit, :update]
  before_action :parse_member_params, only: [:create, :update]

  # GET /messages
  # GET /messages.json
  def index
    messages = ( can? :manage, Message ) ? Message.all : Message.for_member(current_member)
    @messages = messages.by_created.paginate(page: params[:page], per_page: 15)

    current_member.last_message = @messages.first
    current_member.save
  end

  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
    @message.member_ids = params[:members]
    @message.subject    = params[:subject]
    @message.message    = params[:message]
  end

  # GET /messages/1/edit
  def edit
    unauthorized if @message.approved?
    @members = Member.all
  end

  # POST /messages
  # POST /messages.json
  def create
    @members = Member.all
    @message = Message.new(message_params)
    @message.sender = current_member

    respond_to do |format|
      if @message.save
        # Send managers an email letting them know there's a new message
        BackstageMailer.waiting_for_approval(@message).deliver_later unless can? :approve, @message

        format.html { redirect_back_to messages_path, flash: { success: 'Message was successfully created.' } }
        format.json { render action: 'show', status: :created, location: @message }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_back_to messages_path, flash: { success: 'Message was successfully updated.' } }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    unauthorized && return if @message.approved?
    @members = Member.all
    @message.destroy
    respond_to do |format|
      format.html { redirect_back_to messages_url }
      format.json { head :no_content }
    end
  end

  def approve
    @message = Message.find(params[:message_id])
    if can? :approve, @message
      if @message.approved?
        flash[:notice] = "Message was already approved by #{@message.approver.name}"
      else
        @message.approver = current_member
        @message.approved_at = Time.now
        if @message.save
          BackstageMailer.announcements(@message).deliver_later
          flash[:success] = 'Message Approved and Sent'
        else
          flash[:error] = 'Unable to approve message'
        end
      end
    end
    respond_to do |format|
      format.html { redirect_to messages_path }
      format.js { render :layout => false }
    end
  end

  def resend_email
    @message = Message.find(params[:message_id])

    if can? :send, @message
      if @message.delivered?
        redirect_to messages_path, flash: { info: 'Email(s) have already been delivered' }
        return
      end

      if !@message.sent_at.nil? and ( Time.now() - @message.sent_at ) < 600
        redirect_to messages_path, flash: { info: 'Please wait 10 minutes between retrys' }
        return
      end

      if @message.save
        BackstageMailer.announcements(@message).deliver_later
        redirect_to messages_path, flash: { success: 'Email(s) Sent' }
      else
        redirect_to messages_path, flash: { error: 'Unable to send email(s)!' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    def set_members
      @members = Member.active.by_name
      @skills = Skill.all.by_code
      @roles = Role.viewable(current_member)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.required(:message).permit(:subject, :message, member_ids: [])
    end

    def filter_inactive_members(member_ids)
      member_ids.select{ |id| Member.find(id).try(:active?) }
    end

    def parse_member_params
      members =  (params[:message][:member_ids] || []).map { |id| id.to_i unless id.blank? }
      members << (params[:skill_ids]  || []).map { |id| Skill.find(id).member_ids }
      members << (params[:role_ids]   || []).map { |id| Role.find(id).member_ids }
      params[:message][:member_ids] = filter_inactive_members(members.flatten.compact.uniq)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper

  def markdown(text, format=nil)
    require 'redcarpet/render_strip'
    if format.nil?
      renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: false)
      options = {
          autolink: true,
          no_intra_emphasis: true,
          fenced_code_blocks: true,
          lax_html_blocks: true,
          strikethrough: true,
          superscript: true
      }
    else
      renderer = Redcarpet::Render::StripDown.new()
      options = {}
    end

    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end

end

app/views/messages/_form.html.haml
= simple_form_for @message do |f|
  - if @message.errors.any?
    = render 'partials/form_errors', model: @message

  .row
    %p.col-sm-6.col-sm-offset-2.form-hint To send to all Company Members, Leave "Message For" fields empty

  .row
    .col-sm-2.text-right= f.label 'Message For'
    .col-sm-3= f.association :members,
              label: false,
              collection: @members,
              input_html: { class: 'chosen-select', :multiple => :true, data: { placeholder: 'All Company Members' } }
    .col-sm-3= select_tag :skill_ids,  options_from_collection_for_select(@skills, :id, :name),
              class: 'form-control chosen-select',
              :multiple => true,
              data: { placeholder: 'Skills' }
    .col-sm-3= select_tag :role_ids,  options_from_collection_for_select(@roles, :id, :title),
              class: 'form-control chosen-select',
              :multiple => true,
              data: { placeholder: 'Groups' }
    .col-sm-1.chosen-reset= link_to get_icon('remove-circle', text: 'Reset'), '#'

  .row
    .col-sm-2.text-right=f.label 'Subject', required: true
    .col-sm-9= f.input :subject, label: false, placeholder: 'Subject'

  .row
    .col-sm-2.text-right=f.label 'Message', required: true
    .col-sm-9= f.input :message, label: false, placeholder: 'Enter your message here (HTML and Markdown formats supported)', input_html: { rows: 10 }

  .row
    .col-sm-2.col-sm-offset-2
      = button_tag :type => :submit, class: 'btn btn-default' do
        = get_icon(:send, text: 'Send Announcement')

app/views/messages/approve.js.erb
window.location.reload()

app/views/messages/edit.html.haml
%h1 Editing Message

= render 'form'

.pad-top-20
  .pull-right= link_to get_icon(:show, text: 'Show'), @message
  = link_to_back

app/views/messages/index.html.haml
#announcements
  - if can? :create, Message
    .pull-right
      = link_to new_message_path, class: 'btn btn-info' do
        = get_icon :plus, text: 'Add New Announcement'

  %h1 Announcements

  .row
    %strong
      .col-sm-2 Date Created
      .col-sm-8 Message
      .col-sm-2 Status
    %hr

  - @messages.each do |message|
    .box{ class: message.status_class }
      - if !message.approved?
        .controls= render 'partials/admin_commands', klass: message
      .row
        .col-sm-2= link_to message.time_stamp(:created, :long), message_path(message)
        .col-sm-8
          .signature #{link_to_member message.sender} wrote:
          .panel.padding-5
            .message-subject= message.subject
            .message-body= sanitize message.formatted_text
          %span.member-count{ rel: 'popover', title: "Sent to the following #{pluralize(message.members.count, 'Member')}",
            data: { container: 'body', toggle: 'popover', placement: 'auto left', trigger: 'click',
                    content: message.members.collect{|m| m.name}.to_sentence } }
            = get_icon :envelope, text: "Sent to #{pluralize(message.members.count, 'Member')}"
        .col-sm-2
          - if !message.approved?
            .status Waiting on Approval
            - if can? :manage, message
              .admin-controls
                = link_to get_icon( 'thumbs-up', title: 'Approve' ),
                    message_approve_path(message),
                    data: { disable_with: '...', remote: true }
          - else
            - if message.delivered?
              - if can? :manage, message
                .status Delivered at #{message.time_stamp(:delivered)}
              - else
                .status Delivered
            - else
              .status= message.sent? ? "Sent at #{message.time_stamp(:sent)}" : 'Not Sent Yet'

              - if can? :manage, message
                .admin-controls= link_to get_icon( :email, title: 'Retry' ), message_resend_email_path(message)

            - if can? :manage, message
              .status.approval Approved by<br>#{link_to_member message.approver}

  = will_paginate @messages, renderer: BootstrapPagination::Rails

app/views/messages/new.html.haml
%h1 New Message

= render 'form'

.pad-top-20= link_to_back

app/views/messages/show.haml
#message
  %h1
    = @message.subject

  .row
    .col-md-8
      .body.panel
        = sanitize @message.formatted_text
    .col-md-4
      .box{ class: @message.status_class }
        %h3.no-pad-top= @message.time_stamp(:created, :long)
        .time
          .row
            .col-xs-4 Sent
            .col-xs-8= @message.time_stamp(:sent)
          .row
            .col-xs-4 Delivered
            .col-xs-8= @message.time_stamp(:delivered)

  .pad-top-20 Sent To:
  .col-sm-12.box
    - @message.members.each do |member|
      .col-lg-2.col-md-4.col-sm-6= link_to_member member

  .row
    .col-md-12
      Approved by #{link_to_member @message.approver}
      - if can? :approve, @message and @message.approved_at
        on #{@message.time_stamp(:approved, :long)}

  .pad-top-20= link_to_back