config/routes.rb
require 'api_constraints'

Backstage::Application.routes.draw do

  devise_for :members

  concern :notable do
    resources :notes
  end

  concern :sortable do
    collection { post :reposition }
  end

  # API Calls
  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :members do
        get :conflicts
      end

      get 'event/:id',    to: 'events#event'
      get 'events/:date', to: 'events#events'
    end
  end

  resources :announcements, controller: 'messages', :as => :messages do
    get :approve
    get :resend_email
  end

  resource :inbox, controller: 'inbox', :only => [:show,:create] # For email WebHooks

  resources :skills,  :concerns => :sortable

  resources :show_templates, except: [:show]
  resources :shows,   :concerns => :notable do
    collection do
      get 'create',   to: 'shows#create_shows', as: 'create'
    end
    post 'casting_announcement'
  end

  get '/members/schedule'
  resources :members, :concerns => :notable do
    get :cast_list
    resource :conflicts do
      get :manage_conflicts, :as => :manage
      get :get_conflicts,  :as => :get
      put :set_conflicts,  :as => :set
    end
  end
  get '/conflicts',      to: 'conflicts#index'
  put '/lock_conflicts', to: 'conflicts#lock_conflicts'
  get '/roles',          to: 'members#roles'

  resources :configs, controller: 'konfigs', only: [ :index, :update ] do
    collection do
      patch :update_multiple
    end
  end

  resources :documents, only: [:index, :new, :create, :destroy]   

  # Shifts
  get   '/shifts', to: 'shifts#index'
  patch '/shifts', to: 'shifts#update'
  get 'shifts/schedule'
  get 'shifts/publish'

  # Audit logs
  get '/audit',       to: 'audits#index'
  get '/audit/:type', to: 'audits#index'

  # Used for testing (inactive when in production mode)
  get '/admin', to: 'members#admin'

  root 'members#show'

end

app/models/document.rb
class Document < ActiveRecord::Base
    validates :name, presence: true # Make sure the owner's name is present.
    has_attached_file :attachment
    validates_attachment :attachment, :content_type => {:content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)}   
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
    authorize_resource #Who do we need to authorize, determine if we need to authorize differently for those who can upload vs. those who read
    def index
        @documents = Document.all
    end

    def new
        @document = Document.new
    end

    def create
        @document = Document.new(document_params)
    
        if @document.save
            redirect_to documents_path, notice:"Successfully uploaded"
        else
            render "new"
        end
    end

    def destroy
        @document = Document.find(params[:id])
        @document.destroy
        redirect_to documents_path, notice: "Successfully deleted"
    end

    private
        def document_params
            params.require(:document).permit(:name, :attachment)
        end
end

app/views/documents/index.html.erb
<div class="container">
<% if !flash[:notice].blank? %>
   <div>
      <%= flash[:notice] %>
   </div>
<% end %>
</div>

<br>
<% if current_member.has_role?(:admin) %>
<div class="pull-right">
  <%= link_to new_document_path, class: 'btn btn-info' do %>
    <%= get_icon :plus, text: 'Add New Document' %>
  <% end %>
</div>
<% end %>
<br>
<br>

<h1>Important Documents</h1>
<div class="row">
    <strong>
      <div class="col-sm-6">Document Name</div>
      <div class="col-sm-2">Download Link</div>
      <% if current_member.has_role?(:admin) %>
         <div class="col-sm-2">Action</div>
      <% end %>
    </strong>
    <hr/>
</div>

<%# Need to fix this section %>
<% @documents.each do |document| %>
   <div class="row">
   <div class="col-sm-6">
   <%= document.name %>
   </div>
   <div class="col-sm-2">
    <%= link_to "Download", document.attachment.url %>
   </div>
   <div class="col-sm-2">
   <% if current_member.has_role?(:admin) %>
    <%= link_to "Delete",  document, method: :delete %>
   <% end %>
   </div>
   </div>
<% end %>

app/views/documents/new.html.erb
<div class="container">     
<% if !@document.errors.empty? %>   
   <div>   
         
      <ul>   
         <% @document.errors.full_messages.each do |msg| %>   
            <li><%= msg %></li>   
         <% end %>      </ul>   
         
   </div>   
<% end %>   

<br>   
<h1>New Document</h1>
<div>   
   <%= form_for @document, html: { multipart: true } do |f| %>   
      <%= f.label :name %>   
      <%= f.text_field :name %>   
      <br><br> 
      <%= f.label :attachment %>   
      <%= f.file_field :attachment %>   
      <br>   
      <%= button_tag :type => :submit, class: 'btn btn-default' do %>
      <%= get_icon(:send, text: 'Save Document') %>
      <% end %>
   <% end %>   
</div>   
</div>  