config/routes.rb
require 'api_constraints'

Backstage::Application.routes.draw do

  devise_for :members

  concern :notable do
    resources :notes
  end

  concern :sortable do
    collection { post :reposition }
  end

  # API Calls
  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :members do
        get :conflicts
      end

      get 'event/:id',    to: 'events#event'
      get 'events/:date', to: 'events#events'
    end
  end

  resources :announcements, controller: 'messages', :as => :messages do
    get :approve
    get :resend_email
  end

  resource :inbox, controller: 'inbox', :only => [:show,:create] # For email WebHooks

  resources :skills,  :concerns => :sortable

  resources :show_templates, except: [:show]
  resources :shows,   :concerns => :notable do
    collection do
      get 'create',   to: 'shows#create_shows', as: 'create'
    end
    post 'casting_announcement'
  end

  get '/members/schedule'
  resources :members, :concerns => :notable do
    get :cast_list
    resource :conflicts do
      get :manage_conflicts, :as => :manage
      get :get_conflicts,  :as => :get
      put :set_conflicts,  :as => :set
    end
  end
  get '/conflicts',      to: 'conflicts#index'
  put '/lock_conflicts', to: 'conflicts#lock_conflicts'
  get '/roles',          to: 'members#roles'

  resources :configs, controller: 'konfigs', only: [ :index, :update ] do
    collection do
      patch :update_multiple
    end
  end

  resources :documents, only: [:index, :new, :create, :destroy]   

  # Shifts
  get   '/shifts', to: 'shifts#index'
  patch '/shifts', to: 'shifts#update'
  get 'shifts/schedule'
  get 'shifts/publish'

  # Audit logs
  get '/audit',       to: 'audits#index'
  get '/audit/:type', to: 'audits#index'

  # Used for testing (inactive when in production mode)
  get '/admin', to: 'members#admin'

  root 'members#show'

end

app/models/show.rb
class Show < ActiveRecord::Base
  before_destroy :log_destroy
  before_save    :set_capacity

  store_accessor :tickets

  has_many :shifts, :dependent => :destroy
  has_many :crew_members, :through => :shifts, :source => :member
  has_many :skills, -> { order(:code) }, :through => :shifts
  has_many :scenes, -> { order(:position) }, :dependent => :destroy
  has_many :notes, :as => :notable

  belongs_to :mc, class_name: 'Member', :inverse_of => :mc_shifts
  belongs_to :group, class_name: 'Role'

  has_and_belongs_to_many :actors, class_name: 'Member', join_table: 'actors_shows'

  accepts_nested_attributes_for :scenes, allow_destroy: true
  accepts_nested_attributes_for :shifts, allow_destroy: true

  scope :recent, -> { where('date > ?', Date.today - 5.days) }
  scope :by_date, -> { order(:date, :showtime) }
  scope :by_date_desc, -> { order(:date => :desc, :showtime => :desc) }

  scope :for_date, ->(date) { where(date: date) }
  scope :for_month, ->(cdate = Date.today) { where('date >= ? AND date <= ?', cdate.beginning_of_month, cdate.end_of_month) }

  # default_scope { by_date }

  validates_presence_of :date, :name

  def call_time
    calltime.strftime('%l:%M %P')
  end

  def show_time
    showtime.strftime('%l:%M %P')
  end

  def casting_sent
    casting_sent_at.strftime('%m/%d/%Y @ %l:%M %P')
  end

  def gregorian_date
    date.strftime('%m/%d/%Y')
  end

  def human_date
    case date
      when Date.today     then 'Today'
      when Date.tomorrow  then 'Tomorrow'
      when Date.yesterday then 'Yesterday'
      else gregorian_date
    end
  end

  def year
    date.strftime('%Y').to_i
  end

  def month
    date.strftime('%m').to_i
  end

  def dow
    date.strftime('%A')
  end

  def datetime
    "#{gregorian_date} @ #{show_time}"
  end

  def title
    "#{datetime} - #{name}"
  end

  def cal_title
    "#{show_time} - #{name}"
  end

  def dowtitle
    "#{datetime} #{dow}"
  end

  def shift(code = nil)
    return unless code
    shifts.where(skill: Skill.class_eval(code.to_s.downcase)).first
  end

  def cast?
    !casting_sent_at.nil?
  end

  def to_datetime(time = :showtime)
    DateTime.new(date.year, date.month, date.day, self.send(time).in_time_zone('UTC').hour, self.send(time).in_time_zone('UTC').min)
  end

  def is_soon?
    ( 6.hours.ago.to_datetime.utc .. 24.hours.from_now.to_datetime.utc ).cover?(to_datetime)
  end

  def is_today?
    date == Date.today
  end

  def self.ticket_types
    %w(sold comp rush walkup)
  end

  def tickets_total
    Show.ticket_types.map { |t| tickets_for_type(t) }.inject(:+)
  end

  def sold_out?
    tickets_total >= ( capacity || Konfig.default_show_capacity )
  end

  # Provides accessor methods for all ticket_types
  def method_missing(method, *args)
    if Show.ticket_types.include?(method.to_s)
      tickets_for_type(method.to_s)
    else
      super
    end
  end

  def respond_to?(method, include_private = false)
    if Show.ticket_types.include?(method.to_s)
      true
    else
      super
    end
  end

  private

  def tickets_for_type(type)
    return 0 if tickets.nil?
    tickets.has_key?(type.to_s) ? tickets[type.to_s].to_i : 0
  end

  def set_capacity
    self.capacity ||= Konfig.default_show_capacity
  end

  def log_destroy
    Audit.logger self.class.to_s, "Deleted #{self.title}"
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  authorize_resource

  before_action :set_show, only: [:show, :edit, :update, :destroy]
  before_action :set_supporting, except: [ :schedule ]
  before_action :set_exceptions, only: [ :index, :schedule ]

  # GET /shows
  # GET /shows.json
  def index
    session[:date_params] = params[:date]
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
    @notable = @show
    @notes = @notable.notes
    @note = Note.new
  end

  # GET /shows/new
  def new
    @show = Show.new
    @show.tickets = {}
    @show.showtime = '8:00pm'
    @show.calltime = '6:30pm'
  end

  # GET /shows/1/edit
  def edit
    @show.capacity ||= Konfig.default_show_capacity
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render action: 'show', status: :created, location: @show }
      else
        format.html { render action: 'new' }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_back_to shows_url }
      format.json { head :no_content }
    end
  end

  def create_shows
    unauthorized unless can? :create, Show
    date = ( Date.parse(params[:date]) || Date.today )
    Audit.logger :show, "Begin create shows for #{date.strftime('%B %Y')}"
    ShowTemplate.create_shows_for(date.month, date.year)
    flash.notice = "Created shows for #{date.strftime('%B %Y')}"
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def casting_announcement
    return unless params[:show_id]

    @show = Show.find(params[:show_id])
    unauthorized && return unless can? :cast, @show

    @show.casting_sent_at = Time.now

    Audit.logger :show, "Sent casting announcement for #{@show.title}"

    if BackstageMailer.casting_announcement(@show).deliver_later
      @show.save
      redirect_to :back, flash: { success: 'Casting Announcement Sent' }
    else
      redirect_to :back, flash: { error: 'Unable to send email(s)!' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id]) rescue nil
      return if @show.nil?

      @actors = @show.actors.by_name
      @shifts = @show.shifts.by_skill_priority
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      # ticket_keys = params[:show][:tickets].try(:keys)
      params.require(:show).permit(
          :name, :date, :showtime, :calltime, :mc_id, :group_id, :capacity, actor_ids: [],
          shifts_attributes: [ :id, :training, :member_id, :skill_id, :_destroy ],
          #scenes_attributes: [
          #    :id, :_destroy, :stage_id, :position, :suggestion,
          #    notes_attributes: [ :id, :content, :_destroy ]
          #]
      ).tap { |whitelist| whitelist[:tickets] = params[:show][:tickets] }
    end

    def set_supporting
      @stages   = Stage.all
      @skills   = Skill.all.by_code
      @crewable = Member.crewable.by_name.to_a.uniq
      @castable = Member.castable.by_name.to_a.uniq
      @groups   = Role.castable
      @mcs = Member.active.has_role(:mc)
    end

    def set_exceptions
      @exceptions = []
      @date = params[:date] ? Date.parse(params[:date]) : Date.today
      @date_string = @date.strftime("%B %Y")
      @shows = Show.for_month(@date).order(:date, 'showtime ASC')
    end

end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_form.haml
= simple_form_for @show do |f|
  - if @show.errors.any?
    = render 'partials/form_errors', model: @show

  .row
    .col-md-6= f.input :name, disabled: !(can? :manage, @show)
    .col-md-6.box
      - if can? :sell, @show
        .col-md-3= f.input :capacity
        = f.simple_fields_for :tickets do |ticket|
          - Show.ticket_types.each do |type|
            = ticket.input type,
              required: false,
              input_html: { value: @show.send(type) },
              wrapper_html: { :class => 'col-md-' + ( 9 / Show.ticket_types.count ).to_i.to_s }
  .row
    .col-md-3= f.input :date,     :as => :string, label: 'Show Date', disabled: !(can? :manage, @show), input_html: { class: 'datepicker' }
    .col-md-3= f.input :showtime, :as => :string, label: 'Show Time', disabled: !(can? :manage, @show), input_html: { class: 'timepicker' }
    .col-md-3= f.input :calltime, :as => :string, label: 'Call Time', disabled: !(can? :manage, @show), input_html: { class: 'timepicker' }
    .col-md-3
      = f.association :group,
        :collection    => @groups,
        :include_blank => true,
        :label_method  => :title,
        :disabled      => !(can? :manage, @show),
        :input_html    => { class: 'chosen-select', multiple: false, data: { placeholder: 'All Groups' } }

  .row
    .col-md-4
      %fieldset
        %legend Cast the Show:
        #cast
          = f.association :mc,
              :collection => @mcs,
              :include_blank => true,
              :label_method => :name,
              :disabled => !(can? :manage, @show),
              :label => 'MC ',
              :input_html => { class: 'chosen-select', multiple: false, data: { placeholder: 'Select MC', check_conflicts: @show.id } }

          = f.association :actors,
              :collection => @castable,
              :include_blank => true,
              :label_method => :casting_tag,
              :disabled => !(can? :cast, @show),
              :label => 'Actors ',
              :input_html => { class: 'chosen-select', multiple: true, data: { placeholder: 'Select Actors' } }

    .col-md-8
      %fieldset
        %legend Crew the Show
        #crew
          = f.simple_fields_for :shifts do |shift|
            = render 'shift_fields', f: shift
          - if can? :manage, @show
            .pull-left.links= link_to_add_association get_icon(:add, text: 'Add Shift'), f, :shifts

  -#.row
  -#  %fieldset
  -#    %legend Write the Show
  -#    = f.simple_fields_for :scenes do |builder|
  -#      = render 'scene_fields', f: builder
  -#    .links= link_to_add_association button_tag('Add Scene'), f, :scenes

  .action
    = f.submit class: 'btn btn-default'

app/views/shows/_form.html.haml
= simple_form_for @show do |f|
  - if @show.errors.any?
    = render 'partials/form_errors', model: @show

  .row
    .col-md-4= f.input :date,     :as => :string, label: 'Show Date', input_html: { class: 'datepicker' }
    .col-md-4= f.input :showtime, :as => :string, label: 'Show Time', input_html: { class: 'timepicker' }
    .col-md-4= f.input :calltime, :as => :string, label: 'Call Time', input_html: { class: 'timepicker' }

  .row
    .col-md-6
      %fieldset
        %legend Crew the Show
        #crew
          = f.simple_fields_for :shifts do |shift|
            = render 'shift_fields', f: shift
          .links= link_to_add_association content_tag(:span, nil, class: 'glyphicon glyphicon-plus') + ' Add Shift', f, :shifts

    .col-md-6
      %fieldset
        %legend Cast the Show:
        #cast
          = f.association :actors,
              :collection => @members_castable,
              :as => :grouped_select,
              :label_method => :name,
              :group_method => :members,
              :include_blank => true,
              :label => 'Actors ',
              :input_html => { class: 'chosen-select', multiple: :true, data: { placeholder: 'Select Members' } }

  -#.row
  -#  %fieldset
  -#    %legend Write the Show
  -#    = f.simple_fields_for :scenes do |builder|
  -#      = render 'scene_fields', f: builder
  -#    .links= link_to_add_association button_tag('Add Scene'), f, :scenes

  .action
    = f.submit class: 'btn btn-default'

app/views/shows/_scene_fields.haml
.nested-fields
  .field
    = f.association :stage, collection: @stages
    = f.hidden_field :position

  .field
    = f.label "Suggestions:"
    = f.input_field :suggestion

  .notes
    = f.simple_fields_for :notes do |builder|
      = render 'notes/note_fields', f: builder
    = link_to_add_association button_tag('Add Note'), f, :notes,
      :partial => 'notes/note_fields', 'data-association-insertion-method' => :append

  = link_to_remove_association button_tag('Delete Scene'), f

app/views/shows/_shift_fields.haml
.nested-fields
  .row.field
    .col-md-5
      = f.association :skill, collection: @skills, include_blank: false, label: false,
        disabled: !(can? :manage, @show),
        input_html: { class: 'chosen-select' },
        :wrapper_html => { :style => 'display: inline' }

    .col-md-5
      = f.association :member, collection: @crewable, include_blank: true, label: false,
        disabled: !(can? :manage, @show),
        input_html: { class: 'chosen-select', data: { placeholder: 'No one scheduled', check_conflicts: @show.id } },
        :wrapper_html => { :style => 'display: inline' }

    .col-md-2
      .pull-left= f.input :training, label: 'Train?', disabled: !(can? :manage, @show)

      - if can? :manage, @show
        .text-right= link_to_remove_association get_icon(:remove, title: 'Remove Shift'), f

app/views/shows/_show_calendar.haml
#calendar
  = calendar( date: @date, events: @shows ) do |date|
    .cal-date= date.day
    - @shows.for_date(date).each do |show|
      = link_to show.cal_title, "#show-#{show.id.to_s}", class: ['cal-listing', 'scroll-to-link', ( show.group.name if show.group )]

app/views/shows/create_shows.js.erb
window.location.reload();

app/views/shows/edit.html.haml
%h1 Edit Show

= render 'form'

.pad-top-20
  .pull-right= link_to get_icon(:show, text: 'Show'), @show
  = link_to_back

app/views/shows/index.haml
#scheduler.errors

#shows-index
  =link_to '', name: 'top'

  -if can? :generate, Show
    .pull-right
      = link_to create_shows_path(date: @date), class: 'btn btn-info', data: { disable_with: 'Processing', remote: true } do
        = get_icon 'calendar', text: "Create Shows for #{@date.strftime('%B %Y')}"

  %h1 Shows in #{@date.strftime('%B, %Y')}
  = render 'partials/month_controls'

  .hidden-xs.hidden-sm
    = render 'show_calendar'
    %h2 Shows by Date

  .table-responsive
    %table.table.table-striped
      %thead
        %tr
          %th Date
          %th Name
          %th.hidden-xs.hidden-sm Call Time
          %th.hidden-xs.hidden-sm Show Time
          %th Crew
          %th Cast
          %th.hidden-xs.hidden-sm # Tix
          %th
            - if can? :create, Show
              .text-right= link_to_new new_show_path

      %tbody
        - @shows.each do |show|
          %tr{ class: ('is-soon' if show.is_today? ), id: 'show-' + show.id.to_s }
            %td= link_to show.gregorian_date, show_path(show)
            %td= link_to show.name, show_path(show)
            %td.hidden-xs.hidden-sm= format_time_ampm show.calltime
            %td.hidden-xs.hidden-sm= format_time_ampm show.showtime
            %td
              %ul.list-unstyled
                - show.shifts.by_skill_priority.each do |shift|
                  %li
                    .shift-code
                      %span{ rel: 'tooltip', title: shift.skill.name, data: { toggle: 'tooltip', placement: 'left' } }= shift.skill.code + ':'
                    .shift-name
                      - if shift.member.nil? or ( shift.hidden and cannot? :manage, show )
                        = content_tag( :span, 'Not Assigned', class: 'red' )
                      - else
                        = link_to_member( shift.member )
                        = get_icon(:hidden, class: 'small') if shift.hidden
                      = ' (T)' if shift.training?

            %td
              %ul.list-unstyled
                - if !show.mc.nil?
                  %li= link_to_member( show.mc ) + ' (MC)'
                - show.actors.each do |actor|
                  %li= link_to_member actor

            %td.hidden-xs.hidden-sm{class: ('red' if show.sold_out?)}
              = show.tickets_total

            %td
              - if show.notes.any?
                %span.pull-left{ rel: 'popover', title: 'Notes',
                  data: { container: 'body', toggle: 'popover', placement: 'auto left', trigger: 'click',
                          content: show.notes.order(:created_at).collect{|n| n.content}.join('<hr/>') }}
                  = get_icon(:comment)
              = render 'partials/admin_commands', klass: show, show: true, uparrow: true

  = link_to 'Top', '', class: 'scroll-to-top'
  = render 'partials/month_controls'

app/views/shows/index.html.haml
-#= render 'schedule_exceptions' unless @exceptions.empty?

#scheduler.errors

#shows-index

  -if can? :manage, Show
    .pull-right
      = link_to schedule_shows_path, class: 'btn btn-info auto-schedule', data: { disable_with: 'Processing', remote: true } do
        = content_tag( :span, nil, class: 'glyphicon glyphicon-calendar' ) + ' Auto Schedule'

  -#%h1.col-md-4 #{@date.strftime('%B')} Show Schedule
  .month-controls
    %h2
      = link_to content_tag( :span, nil, class: 'glyphicon glyphicon-circle-arrow-left'), { date: @date.prev_month }
      #{@date.strftime('%B %Y')} Show Schedule
      = link_to content_tag( :span, nil, class: 'glyphicon glyphicon-circle-arrow-right'), { date: @date.next_month }

  .table-responsive
    %table.table.table-striped
      %thead
        %tr
          %th Date
          %th Name
          %th.hidden-xs.hidden-sm Call Time
          %th.hidden-xs.hidden-sm Show Time
          %th Crew
          %th Cast
          %th
            - if can? :create, Show
              .text-right= link_to content_tag( :span, nil, class: 'glyphicon glyphicon-plus') + ' Add New Show', new_show_path

      %tbody
        - @shows.each do |show|
          %tr
            %td= link_to show.human_date, show_path(show)
            %td= link_to show.name, show_path(show)
            %td.hidden-xs.hidden-sm= format_time_ampm show.calltime
            %td.hidden-xs.hidden-sm= format_time_ampm show.showtime
            %td
              %ul.list-unstyled
                - show.shifts.by_skill_priority.each do |shift|
                  %li
                    .shift-code= shift.skill.code + ':'
                    .shift-name= shift.member.nil? ? content_tag( :span, 'Not Assigned', class: 'red' ) : link_to( shift.member.name, member_path(shift.member) )

            %td
              %ul.list-unstyled
                - show.actors.each do |actor|
                  %li= link_to actor.name, member_path(actor)

            %td= render 'partials/admin_commands', klass: show

app/views/shows/new.html.haml
%h1 New show

= render 'form'

.pad-top-20= link_to_back

app/views/shows/show.haml
#ticket-sales
  .box{class: ('sold-out' if @show.sold_out?)}
    .header Ticket Sales as of #{@show.updated_at.strftime('%m/%d/%Y @ %T')}
    %ul.list-inline.sales
      - Show.ticket_types.each do |type|
        %li.sale
          .type #{type.capitalize}:
          .count #{@show.send(type)}

%h1
  = @show.gregorian_date
  %small= @show.name

%ul.list-inline.pad-top-20
  %li Show Time: #{format_time_ampm @show.showtime}
  %li Call Time: #{format_time_ampm @show.calltime}

.row
  .col-md-6
    .box
      .row
        .col-md-2 MC
        .col-md-10= link_to_member @show.mc
      .row
        %br
        .col-md-2 Cast
        .col-md-10
          - @actors.each do |cast|
            .row
              .col-md-6= link_to_member( cast )
              .col-md-6.hidden-xs= cast.roles.castable.map { |r| r.title }.to_sentence

  .col-md-6
    .box
      .row
        .col-md-2 Crew
        .col-md-10
          - @shifts.each do |shift|
            .row
              .col-sm-6.hidden-xs
                = shift.skill.name
                = ' (T)' if shift.training?
              .col-xs-4.visible-xs
                = shift.skill.code
                = ' (T)' if shift.training?
              .col-xs-8.col-sm-6= shift.hidden? ? 'Not Published' : link_to_member( shift.member )

.row
  .col-xs-12.col-sm-6.col-md-4
    - if @show.actors.any?
      - if can? :cast, @show
        = link_to get_icon(:email, text: @show.cast? ? "Cast sent at #{@show.casting_sent}" : 'Send Cast Announcement' ),
                  show_casting_announcement_path(@show),
                  class: 'btn btn-default',
                  method: :post,
                  title: ( 'Re-Send?' if @show.cast? ),
                  data: { disable_with: 'Sending emails, please wait', confirm: ('Re-Send Announcement?' if @show.cast?) }
  .col-xs-6.col-sm-3.col-md-2.col-md-offset-4
    - if @show.actors.any?
      - if can? :cast, @show
        %span.pad-top-20.visible-xs
      = link_to get_icon(:email, text: 'Email Cast'),
        new_message_path( subject: "Re: #{@show.gregorian_date}", members: @show.actors.map(&:id) ),
        class: 'btn btn-default'
  .col-xs-6.col-sm-3.col-md-2.text-right
    - if @show.crew_members.any?
      - if can? :cast, @show
        %span.pad-top-20.visible-xs
      = link_to get_icon(:email, text: 'Email Crew'),
        new_message_path( subject: "Re: #{@show.date}", members: @show.crew_members.map(&:id) ),
        class: 'btn btn-default'

.row
  .col-md-12
    .well.pad-top-20
      Notes
      = render 'notes/notes', klass: @show
      = render 'notes/form'

.pad-top-20
  - if can? :update, @show
    .pull-right= link_to get_icon(:edit, text: 'Edit'), edit_show_path(@show)
  = link_to_back