config/routes.rb
require 'api_constraints'

Backstage::Application.routes.draw do

  devise_for :members

  concern :notable do
    resources :notes
  end

  concern :sortable do
    collection { post :reposition }
  end

  # API Calls
  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :members do
        get :conflicts
      end

      get 'event/:id',    to: 'events#event'
      get 'events/:date', to: 'events#events'
    end
  end

  resources :announcements, controller: 'messages', :as => :messages do
    get :approve
    get :resend_email
  end

  resource :inbox, controller: 'inbox', :only => [:show,:create] # For email WebHooks

  resources :skills,  :concerns => :sortable

  resources :show_templates, except: [:show]
  resources :shows,   :concerns => :notable do
    collection do
      get 'create',   to: 'shows#create_shows', as: 'create'
    end
    post 'casting_announcement'
  end

  get '/members/schedule'
  resources :members, :concerns => :notable do
    get :cast_list
    resource :conflicts do
      get :manage_conflicts, :as => :manage
      get :get_conflicts,  :as => :get
      put :set_conflicts,  :as => :set
    end
  end
  get '/conflicts',      to: 'conflicts#index'
  put '/lock_conflicts', to: 'conflicts#lock_conflicts'
  get '/roles',          to: 'members#roles'

  resources :configs, controller: 'konfigs', only: [ :index, :update ] do
    collection do
      patch :update_multiple
    end
  end

  resources :documents, only: [:index, :new, :create, :destroy]   

  # Shifts
  get   '/shifts', to: 'shifts#index'
  patch '/shifts', to: 'shifts#update'
  get 'shifts/schedule'
  get 'shifts/publish'

  # Audit logs
  get '/audit',       to: 'audits#index'
  get '/audit/:type', to: 'audits#index'

  # Used for testing (inactive when in production mode)
  get '/admin', to: 'members#admin'

  root 'members#show'

end

app/models/conflict.rb
class Conflict < ActiveRecord::Base
  before_create  :log_create
  before_destroy :log_destroy

  belongs_to :member

  scope :for_date, ->(date = Date.today) do
    if my_date = Date.parse(date.to_s)
      where(year: my_date.year).where(month: my_date.month).where(day: my_date.day)
    end
  end
  scope :for_month, ->(month, year = Date.today.year) { where(year: year).where(month: month) }
  scope :for_year,  ->(year) { where(year: year) }

  scope :next_month, -> { for_month( (Date.today - 1.month).month, (Date.today - 1.month).year) }
  scope :this_month, -> { for_month( Date.today.month ) }
  scope :next_month, -> { for_month( (Date.today + 1.month).month, (Date.today + 1.month).year) }
  scope :this_year,  -> { for_year( Date.today.year ) }

  scope :current, -> { this_month | next_month }
  scope :current_and_future, -> { current | future }
  scope :future,  -> { where('year >= ?', Date.today.year).where('month > ?', Date.today.month) }

  scope :by_date, -> { order([:year, :month, :day]) }

  # default_scope -> { by_date }

  def date
    '%4d-%02d-%02d' % [year, month, day]
  end

  def us_date
    '%02d/%02d/%4d' % [month, day, year]
  end

  def datetime
    date.to_time
  end

  def locked?
    lock?
  end

  def lock!
    return if locked?
    Audit.logger self.class.to_s, "Conflict for #{self.member.name} on #{self.date} locked in"
    self.lock = true
    self.save
  end

  def log_create
    return if ENV['RAILS_ENV'] == 'test'
    Audit.logger self.class.to_s, "Conflict created for #{self.member.name} on #{self.date}"
  end

  def log_destroy
    return if ENV['RAILS_ENV'] == 'test'
    Audit.logger self.class.to_s, "Conflict removed for #{self.member.name} on #{self.date}"
  end

end

app/controllers/conflicts_controller.rb
class ConflictsController < ApplicationController
  authorize_resource

  before_action :get_member, :except => [ :index, :lock_conflicts ]
  before_action :get_config
  before_action :authorize

  # GET /conflicts
  # GET /conflicts.json
  def index
    unauthorized && return unless can? :manage, Conflict
    @members = Member.by_name.uses_conflicts.paginate(:page => params[:page], :per_page => 50)
    respond_to do |format|
      format.html
      format.json {}
      format.js   {}
    end
  end

  def manage_conflicts
    unauthorized unless can? :read, @member
    @conflicts = @member.conflicts
    @date = params[:date] ? Date.parse(params[:date]) : Date.today + 1.month # By default, select next month
    @conflicts_this_month = @conflicts.for_month(@date.month, @date.year)
    @cur_conflicts = @conflicts_this_month.count
  end

  def get_conflicts
    respond_to do |format|
      format.html { render 'public/403' }
      format.json { render json: @member.conflicts }
      format.js   { render json: @member.conflicts }
    end
  end

  def set_conflicts
    @conflict_date = params[:date]
    @conflict = @member.conflicts.for_date(@conflict_date).first

    if @conflict
      @conflict.destroy if current_member.is_admin? or !@conflict.locked?
    else
      conflict_date = Date.parse(@conflict_date)
      unless Conflict.create( month: conflict_date.month,
                              day:   conflict_date.day,
                              year:  conflict_date.year,
                              member: @member )
        flash[:alert] = 'Oops, there was a problem updating conflicts'
      end
    end

    respond_to do |format|
      format.html { redirect_to manage_member_conflicts_path(@member) }
      format.js {}
    end
  end

  def lock_conflicts
    unauthorized unless can? :lock, Conflict
    Conflict.find_each(&:lock!)
    respond_to do |format|
      format.html { redirect_to conflicts_path, notice: 'All existing conflicts have been locked.' }
      format.js {}
    end
  end

  private
    def authorize
      unauthorized unless can? :update, Conflict
    end

    def get_config
      @max_conflicts = Konfig.member_max_conflicts
    end

    def get_member
      @member = Member.friendly.find(params[:member_id]) || Member.none
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conflict_params
      params.require(:conflicts).permit(:date, :member_id)
    end
end

app/helpers/conflicts_helper.rb
module ConflictsHelper
end

app/views/conflicts/_form.html.haml
= form_for @conflict do |f|
  - if @conflict.errors.any?
    = render 'partials/form_errors', model: @conflict

  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :member
    = f.text_field :member
  .actions
    = f.submit 'Save'

app/views/conflicts/index.haml
- member_min_shifts = Konfig.member_min_shifts

#conflicts-index
  %h1 Member Conflicts

  = will_paginate @members, renderer: BootstrapPagination::Rails

  %table.table.table-striped
    %thead
      %tr
        %th Member Name
        %th
          Conflicts (
          %span.darkgreen Locked
          \/
          %span.red Unlocked
          )
        %th # Shifts
        %th
          - if can? :lock_conflicts, Conflict
            = link_to get_icon(:lock, text: 'Lock All'), lock_conflicts_path, method: :put

    %tbody
      - @members.to_a.uniq.each do |member|
        - months = []; member_conflicts = member.conflicts.current_and_future
        - member_conflicts.group_by{ |c| c.month }.each { |k,v| months << k if v.count > @max_conflicts }

        %tr
          %td.name= link_to member.name, member
          %td.col-md-6.upcoming
            - if member_conflicts.empty?
              No Conflicts
            - else
              %ul.list-unstyled
                - member_conflicts.group_by{|c| c.month}.each do |month, conflicts|
                  %li{ class: months.include?(month) ? 'red-bg' : nil }
                    %ul.list-inline.conflict-dates
                      - conflicts.each do |conflict|
                        %li{ class: conflict.locked? ? 'darkgreen' : 'red' }= conflict.us_date
          %td
            %ul.list-unstyled
              - member.shifts.future.group_by{|s| s.show.date.month}.each do |month, shifts|
                %li= link_to "#{Date::MONTHNAMES[month]}: #{shifts.count}", shifts_path(date: shifts.first.date)
          %td.manage= link_to 'Conflicts', manage_member_conflicts_path(member)

  = will_paginate @members, renderer: BootstrapPagination::Rails

app/views/conflicts/manage.haml
%h1.text-center= @member.name

#conflicts
  - if @member.is_crewable? or @member.is_castable?

    #calendar
      = render 'partials/month_controls'

      - max_note_message = [ "You've selected <span class='cur-count'>#{@cur_conflicts}</span> out of your <span class='max-count'>#{@max_conflicts}</span> conflicts.",
        "You've allocated all <span class='max-count'>#{@max_conflicts}</span> of your conflicts.",
        "Whoa!  You've selected <span class='cur-count'>#{@cur_conflicts}</span> conflicts, but you're only allowed <span class='max-count'>#{@max_conflicts}</span>!", ]

      = content_tag('div', id: 'max-note',
          class: [ @cur_conflicts  < @max_conflicts ? 'under-limit' : nil,
                   @cur_conflicts == @max_conflicts ? 'at-limit'    : nil,
                   @cur_conflicts  > @max_conflicts ? 'over-limit'  : nil ],
          data: { max_conflicts: @max_conflicts,
                  note_underlimit: h(max_note_message[0]),
                  note_atlimit:    h(max_note_message[1]),
                  note_overlimit:  h(max_note_message[2]) } ) do

        .visible-xs.text-center
          Selected
          %span.cur-count= @cur_conflicts
          = 'of'
          %span.max-countM= @max_conflicts
          conflicts.

        .hidden-xs
          %span.note-message
            - if @cur_conflicts < @max_conflicts
              = max_note_message[0].html_safe
            - elsif @cur_conflicts == @max_conflicts
              = max_note_message[1].html_safe
            - else
              = max_note_message[2].html_safe

          = content_tag('span', class: 'over-limit-note', style: @cur_conflicts <= @max_conflicts ? 'display: none' : nil ) do
            Any beyond the first #{@max_conflicts} may be ignored during scheduling.


      = calendar( date: @date, events: @conflicts ) do |date|
        -if current_member.is_admin? or ( Date.today <= date and !@conflicts.for_date(date).first.try(:locked?) )
          = link_to date.day, { date: date, :action => :set_conflicts }, :method => :put, remote: true, onclick: "calendarClick('#{date.to_s}')"
        - else
          = date.day

      .instructions
        %em
          Please tap or click on a day
          = 'You may not choose a date from the past.' unless current_member.is_admin?

      .legend.hidden-xs
        %span.red RED
        days indicate current conflicts.
        %span.darkred DARKRED
        days are locked conflicts (which cannot be changed)

      -#.summary= "Conflicts for #{@date_string}: #{@conflicts_this_month.empty? ? 'None' : @conflicts_this_month.map{ |c| c.datetime.day }.to_sentence}"

  - else
    Hmmm, it doesn't look like #{@member.firstname} has any need for conflicts.
    If you think this may be an error, check his/her Skills and/or Roles.

app/views/conflicts/manage_conflicts.haml
%h1.text-center= @member.name

#conflicts
  - if @member.is_crewable? or @member.is_castable?

    #calendar
      = render 'partials/month_controls'

      - max_note_message = [ "You've selected <span class='cur-count'>#{@cur_conflicts}</span> out of your <span class='max-count'>#{@max_conflicts}</span> conflicts.",
        "You've allocated all <span class='max-count'>#{@max_conflicts}</span> of your conflicts.",
        "Whoa!  You've selected <span class='cur-count'>#{@cur_conflicts}</span> conflicts, but you're only allowed <span class='max-count'>#{@max_conflicts}</span>!", ]

      = content_tag('div', id: 'max-note',
          class: [ @cur_conflicts  < @max_conflicts ? 'under-limit' : nil,
                   @cur_conflicts == @max_conflicts ? 'at-limit'    : nil,
                   @cur_conflicts  > @max_conflicts ? 'over-limit'  : nil ],
          data: { max_conflicts: @max_conflicts,
                  note_underlimit: h(max_note_message[0]),
                  note_atlimit:    h(max_note_message[1]),
                  note_overlimit:  h(max_note_message[2]) } ) do

        .visible-xs.text-center
          Selected
          %span.cur-count= @cur_conflicts
          = 'of'
          %span.max-countM= @max_conflicts
          conflicts.

        .hidden-xs
          %span.note-message
            - if @cur_conflicts < @max_conflicts
              = max_note_message[0].html_safe
            - elsif @cur_conflicts == @max_conflicts
              = max_note_message[1].html_safe
            - else
              = max_note_message[2].html_safe

          = content_tag('span', class: 'over-limit-note', style: @cur_conflicts <= @max_conflicts ? 'display: none' : nil ) do
            Any beyond the first #{@max_conflicts} may be ignored during scheduling.


      = calendar( date: @date, events: @conflicts ) do |date|
        -if current_member.is_admin? or ( Date.today <= date and !@conflicts.for_date(date).first.try(:locked?) )
          = link_to date.day, { date: date, :action => :set_conflicts }, :method => :put, remote: true, onclick: "calendarClick('#{date.to_s}')"
        - else
          = date.day

      .instructions
        %em
          Please tap or click on a day
          = 'You may not choose a date from the past.' unless current_member.is_admin?

      .legend.hidden-xs
        %span.red RED
        days indicate current conflicts.
        %span.darkred DARKRED
        days are locked conflicts (which cannot be changed)

      -#.summary= "Conflicts for #{@date_string}: #{@conflicts_this_month.empty? ? 'None' : @conflicts_this_month.map{ |c| c.datetime.day }.to_sentence}"

  - else
    Hmmm, it doesn't look like #{@member.firstname} has any need for conflicts.
    If you think this may be an error, check his/her Skills and/or Roles.